import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WrapNextUI from "./components/WrapNextUI";
import WrapRainbowkit from "./components/WrapRainbowKit";
import WrapNextTheme from "./components/WrapNextTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blackdit | miniproject",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WrapNextTheme>
        <WrapRainbowkit>
          <WrapNextUI>
            <body className={inter.className}>
              <main className="dark text-foreground bg-background">
                {children}
              </main>
            </body>
          </WrapNextUI>
        </WrapRainbowkit>
      </WrapNextTheme>
    </html>
  );
}
