import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import WrapNextUI from "./components/WrapNextUI";
import WrapRainbowkit from "./components/WrapRainbowKit";
import WrapNextTheme from "./components/WrapNextTheme";
import AuthProvider from "./providers/AuthProvider";

const open = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blackdit | miniproject",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={open.className} suppressHydrationWarning>
        <WrapNextTheme>
          <WrapRainbowkit>
            <AuthProvider>
              <WrapNextUI>
                <main className="light text-primary bg-background">
                  {children}
                </main>
              </WrapNextUI>
            </AuthProvider>
          </WrapRainbowkit>
        </WrapNextTheme>
      </body>
    </html>
  );
}
