import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "../globals.css";
import NavigationBar from "../components/Navbar/Navbar";
import Sidebar from "../components/Sidebar/Sidebar";
import AuthProvider from "../providers/AuthProvider";

const open = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blackdit | miniproject",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <AuthProvider>
    <div className="light text-primary bg-secondary-foreground  ">
      <div>
        <NavigationBar />
        <div className="flex flex-row gap-9">
          <Sidebar />
          <div className="container max-w-7xl  mx-auto  min-h-screen">
            {children}
          </div>
        </div>
      </div>
    </div>
    // </AuthProvider>
  );
}
